// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zeqloqlhnbdeivnyghkx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InplcWxvcWxobmJkZWl2bnlnaGt4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxNTAxNjcsImV4cCI6MjA3MzcyNjE2N30.j96GObK0f5AUgc5O38n6gum3OU4u_5OFyxRaLj76GwY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});